version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build || echo No build step defined
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Preparing artifacts...
artifacts:
  files:
    - '**/*'
